###########
# site.title, site.url, site.author.name

title:   'Jekyll Minimal Theme'
author:
  name:  'Jekyll Minimal Theme Team'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
baseurl: /jekyll-minimal-theme

# site.abouturl is inserted in the About header link
abouturl: http://silshack.github.io/inls161fall2016

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

